### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by flowluap** [Teraskull/PyDebloatX#2]
- disable IE 11 (Powershell): Disable-WindowsOptionalFeature -FeatureName Internet-Explorer-Optional-amd64 –Online

- remove Edge (Powershell):remove-appxpackage [ path:"get-appxpackage *edge* | Select Name, PackageFullName" ]

- remove Cortana (Powershell): remove-appxpackage [ path:"get-appxpackage *cortana* | Select Name, PackageFullName" ]

**Comment by Teraskull** [comment]
Are these safe? I don't want to add something that can potentially break future updates.

**Comment by flowluap** [comment]
Dont implement those without testing. I am currently under Linux, but am interested in contributing to this repo, so i will bee soon testing those and create a pull request. Maybe a feature request label could be helpful? Found this via reddit, nice work so far! :)

**Comment by Teraskull** [comment]
Thanks, sure, I will add the labels and stuff, I opened the repo recently, as it was a personal tool, didn't expect it to blow off like that. Now I have to make it more user friendly :)
