### ISSUE TITLE
What about a portable version 

### ISSUE THREAD

**Issue by vector65536** [Teraskull/PyDebloatX#27]
Hi. as useful and practical this project, what about building a (minimal) portable version of this app (with custom settings)?
just a thought.

**Comment by Teraskull** [comment]
Hi, thanks for this idea, but isn't the setup installer already making it kind of portable? It just creates a folder on the desktop, which you can put on a flash drive, and it will work the same way.

Regarding custom settings, what exactly are you thinking of? Something like saving a preset of selected apps?

**Comment by cjerrington** [comment]
pyinstaller does allow for the ```--onefile``` command but will need to look into adding the dependencies or missing imports more as once compiled the app gave an error stating "Failed to execute script app". 

After looking into this there might need to be changes on how the resources get referenced as the onefile method does create a runtime folder and the files might not be extracted to this location. When adding the icon.ico and the style.css to the same directory as the compiled exe the window launches but then closes out.

**Comment by Teraskull** [comment]
As you said, `--onefile` is not possible with this software, since there is a separate css file. Also, what `--onefile` does, is unpack everything in some temp folder on Windows, which I think is not very portable. A lot better would be just to store the folder from the desktop. It also would take more time to launch, because of the unpacking.

**Comment by cjerrington** [comment]
I agree with @Teraskull and when the app is compiled to the ```--onedir``` it does place it in its own Directory for that portability and not just one file. 

While looking into this there does seem like it could still [be possible](https://blog.aaronhktan.com/posts/2018/05/14/pyqt5-pyinstaller-executable). When running once compiled there is an __MEIPASS folder and we need to add some additional references to a new location but I've yet to get it working completely yet as one file.

**Comment by cjerrington** [comment]
It looks like there are some icons already added as resources to the QT app. Could we add the icon.ico file and the style.css file to the resources for the QT window and this might allow us to either to
1. eliminate an extra image or 
2. keep all the files internal to the project so we might be able to get a single file when compiling. 

Found this article too [https://www.learnpyqt.com/tutorials/packaging-pyqt5-pyside2-applications-windows-pyinstaller/ ](https://www.learnpyqt.com/tutorials/packaging-pyqt5-pyside2-applications-windows-pyinstaller/)

**Comment by cjerrington** [comment]
Okay, I might have figured it out! 

Seems to be an issue with the `--window` command. removing that seems to help. We do see the "command prompt" window before the GUI appears. 

Build command:
```shell
pyinstaller --noconfirm --onefile --name "PyDebloatX" --icon "pydebloatx/icon.ico" --add-data "pydebloatx/icon.ico;." --add-data "pydebloatx/style.css;."  "pydebloatx/app.py"
```

I did update the resource paths to use the function as described in the posted articles.
```python
def resource_path(relative_path):
  if hasattr(sys, 'frozen'):
      return os.path.join(sys._MEIPASS, relative_path)
  return os.path.join(os.path.abspath('.'), relative_path)
```

Then updating the places the icon.ico and style.css files are referenced with an example below. 
```python
self.setWindowIcon(QIcon(resource_path('./icon.ico')))
...
with open(resource_path('./style.css'), 'r') as file:
```

At the first steps we do have a single, portable file. Aesthetically we would want the console window hidden, but the end result is still one file. It is a little slower to open as @Teraskull mentioned as it is extracting files to the %Temp% folder before running. and once we close the application it deletes the the temp directory. 

I can create a pull request if you'd like to make these changes.

**Comment by space9bug** [comment]
The startup process of one file is really slow. You can add a compressed package (compress the files after the build) as a portable version (*.zip or *.7z).

**Comment by Teraskull** [comment]
It would be harder to edit the style.css, as it would need to be generated each time you change something. Also, since the latest PR, there will be language translation files, which won't be possible to pack into the resource file.

**Comment by cjerrington** [comment]
With pull request #36 we can mark this issue as complete. Thanks for the idea @designjeevan and @Teraskull for letting me help!

**Comment by Teraskull** [comment]
Thank you for your work @cjerrington! Closed until any new issues arise.
