### ISSUE TITLE
[FEATURE] Include Cortana app in removal list since it is a standalone app.

### ISSUE THREAD

**Issue by pratyakshm** [Teraskull/PyDebloatX#29]
Hello, in newer versions of Windows (20H1 and up) you can uninstall Cortana app since its standalone. The name is ``Microsoft.549981C3F5F10``. 
I hope this will be implemented. Thanks!

**Comment by Teraskull** [comment]
Hi, I will look into this, since I need to make sure that it is completely safe to remove Cortana, and reinstall with Microsoft Store. Also, there is a lot of users with versions below 20H1, so I will think about how to implement version checking.

**Comment by pratyakshm** [comment]
> Hi, I will look into this, since I need to make sure that it is completely safe to remove Cortana, and reinstall with Microsoft Store. Also, there is a lot of users with versions below 20H1, so I will think about how to implement version checking.

okay that's nice, though reassuring you, it's 100% safe to remove Cortana and you can re-install her from Microsoft Store. It does not cause any issues. I've removed that myself on my own real installation.

**Comment by space9bug** [comment]
Input: `Get-AppxPackage -PackageTypeFilter Main | Select Name, NonRemovable, SignatureKind`
Output: `Name False Store`
It can be safely uninstalled. You can get all the apps that can be uninstalled.

**Comment by Teraskull** [comment]
Okay, so if we add the Cortana checkbox, it will be checked with that command, and only then visible to the user. So that users don't get confused why Cortana checkbox is disabled, if they have Cortana installed on older Windows 10 versions.

**Comment by Teraskull** [comment]
Done in ebc29c2ee882d7e4656d66db5b237e19e5b78f9c.

**Comment by pratyakshm** [comment]
> Done in [ebc29c2](https://github.com/Teraskull/PyDebloatX/commit/ebc29c2ee882d7e4656d66db5b237e19e5b78f9c).

Nice, thanks.
