### ISSUE TITLE
[BUG] Window sizing incorrect when opened over RDP connection

### ISSUE THREAD

**Issue by Snala** [Teraskull/PyDebloatX#30]
**Describe the bug**
When opening the application on a remote computer over RDP, the window is badly sized and cannot be adjusted.

**To Reproduce**
1. Connect to remote session
2. Check out code
3. Run application following readme.md directions
4. Window sizing is shown incorrect and cannot be adjusted.

**Expected behavior**
Window sizing needs to be appropriate on remote connection, so all options can be seen.

**Screenshots**
<img width="1143" alt="Screen Shot 2020-12-30 at 12 11 05 PM" src="https://user-images.githubusercontent.com/11582458/103378710-19025600-4a98-11eb-9ac1-a4c164529dc1.png">

**Desktop (please complete the following information):**
 - Windows 10 Edition: Windows 10 Pro
 - Version [e.g. 1.3.0]: 10.0.19042 Build 19042

**Additional context**
Using a Mac and Microsoft Remote Desktop to view my target Windows 10 computer.

**Comment by Teraskull** [comment]
That is also a known issue when using a 4k monitor. I couldn't test or fix it yet, since I don't own one.

**Comment by Teraskull** [comment]
Could you please test the latest `master` branch if this fixes the issue? Thanks!

**Comment by space9bug** [comment]
This display problem is basically solved. You can adjust the zoom display in the Windows system settings to do code test.

**Comment by Teraskull** [comment]
Tested on Windows zoom 150%, looks like it is fixed. Issue closed.
