### ISSUE TITLE
[BUG] UnicodeDecodeError in line 313 of app.py

### ISSUE THREAD

**Issue by gtorelly** [Teraskull/PyDebloatX#33]
**Describe the bug**
When I try to run the program, it briefly opens the main window and then closes, presenting the following message:
```
  File "e:\OneDrive\Programas\PyDebloatX-1.9.0\pydebloatx\app.py", line 313, in run
    names_list = x.communicate()[0].decode().split()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 74: invalid continuation byte
```

**To Reproduce**
1. Downloaded the 1.9.0 version folder from GitHub
2. Opened the folder "/pydebloatx/" and tried to run app.py.
3. I used VS Code with a proper environment setup that has pyqt5 and Python 3.8.6.

**Expected behavior**
Just hoped the main window would at least open

**Desktop (please complete the following information):**
 - Windows 10 Pro 20H2 in Brazilian Portuguese
 - Version 1.9.0

**Additional context**
When I run the command in Powershell, I get the following: 
[pydebloatbug.txt](https://github.com/Teraskull/PyDebloatX/files/5756148/pydebloatbug.txt)

**Comment by Teraskull** [comment]
Could you please test the latest `master` branch if there is any difference? I am not able to reproduce the issue.

**Comment by gtorelly** [comment]
Ok, the error changed, now I get:
```
  File "e:\OneDrive\Programas\PyDebloatX\pydebloatx\app.py", line 340, in run 
    names_list = json.loads(names_str)
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  
```

So I put print(names_list) in the code, and it printed the following (I removed the lines that list each app, because I think that the problem is in the first line):

```
. : O arquivo C:\Users\Guilherme\Documents\WindowsPowerShell\profile.ps1 nÆo  
pode ser carregado porque a execu‡Æo de scripts foi desabilitada neste        
sistema. Para obter mais informa‡äes, consulte about_Execution_Policies em    
https://go.microsoft.com/fwlink/?LinkID=135170.
No linha:1 caractere:3
+ . 'C:\Users\Guilherme\Documents\WindowsPowerShell\profile.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ErrodeSeguran‡a: (:) [], PSSecurityException    
    + FullyQualifiedErrorId : UnauthorizedAccess
[
    {
        "Name":  "Microsoft.NET.Native.Runtime.1.4",
        "InstallLocation":  "C:\\Program Files\\Windo
...
...
        "InstallLocation":  "C:\\Windows\\SystemApps\\Microsoft.Windows.SecureAssessmentBrowser_cw5n1h2txyewy"    
    },
    {
        "Name":  "Microsoft.Windows.SecHealthUI",
        "InstallLo
Traceback (most recent call last):
  File "e:\OneDrive\Programas\PyDebloatX\pydebloatx\app.py", line 341, in run
    names_list = json.loads(names_str)
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Guilherme\anaconda3\envs\QWSim\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

There seems to be an issue with the script execution, because it was "disabled in my system". It can't load a powershell profile and throws an error. Maybe the unicode error is in the symbol "nÆo" which should actually be "não". Beyond that, I think that the "json.loads" was expecting a list without this phrase before, but I'm not sure, never used this function.
Running in an elevated command prompt doesn't help with the issue.

**Comment by Teraskull** [comment]
What if you remove the following line from line 338:

```python
universal_newlines=True
```

And set the line 339 to:

```python
names_str = x.communicate()[0].decode('utf-8', errors='ignore')
```

**Comment by gtorelly** [comment]
I get the same error, but the output of "print(names_str)" doesn't show "nÆo", now it's "no".

**Comment by space9bug** [comment]
First, you try to run with the packaged installation file to see if there are any exceptions.
If the packaged file works properly, the bug has nothing to do with the code.

Solutions in VS Code:
1. Running PowerShell in administrator mode
2. View system execution policy status `Get-ExecutionPolicy`
3. Modify execution policy status `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`
4. Finally, close PowerShell and VS Code, and then reopen VS Code

**Comment by Teraskull** [comment]
Yea, that might be a permission issue. Most users are not expected to run those commands in Powershell. And without them, we don't have access to the app folders without admin rights.

**Comment by gtorelly** [comment]
Ok, I will try the steps proposed by @space9bug .

**Comment by gtorelly** [comment]
I installed version 1.9.0 and it worked correctly, so I guess it really is a permission issue. Thanks for your help and sorry for the trouble.
