### ISSUE TITLE
app.py not starting

### ISSUE THREAD

**Issue by LxCasino** [Teraskull/PyDebloatX#4]
Hi,
noob here.
I downloaded everything (including requirements), cd into the folder, type `python3 app.py` and nothing happens.

**Comment by Teraskull** [comment]
Since you did not write what you already tried, I will ask:

Is Python3 installed? if you write ```python3 -V``` in the cmd, what is the output?

Is PyQt5 installed? Try doing ```pip install pyqt5``` and show the output. 

Please fill in a bug report issue, with steps to reproduce.

**Comment by Teraskull** [comment]
Ok, I think I found the issue, on Windows you have to use ```python app.py```, or ```py app.py```. I will fix the mistake in the README.

**Comment by LxCasino** [comment]
Hey, thanks for the quick response(s)!

 > Is Python3 installed? if you write `python3 -V` in the cmd, what is the output? 

`python -V` gives me `'Python 3.8.3'`

> Is PyQt5 installed? Try doing `pip install pyqt5` and show the output.

` Installing collected packages: PyQt5-sip, pyqt5`

>Ok, I think I found the issue, on Windows you have to use python app.py, or py app.py. I will fix the mistake in the README.

Thanks a lot mate.

**Comment by Teraskull** [comment]
@LxCasino Is the issue fixed?

**Comment by LxCasino** [comment]
Yes, `python app.py` did it.
