### ISSUE TITLE
Add functionality to check for updates

### ISSUE THREAD

**Issue by space9bug** [Teraskull/PyDebloatX#47]
https://data.jsdelivr.com/v1/package/gh/Teraskull/PyDebloatX

https://api.github.com/repos/Teraskull/PyDebloatX/tags
https://api.github.com/repos/Teraskull/PyDebloatX/releases/latest

**Comment by Teraskull** [comment]
Added a simple update check. I will probably move the check to a separate thread, since it blocks the initial app refreshing.

**Comment by Teraskull** [comment]
Done in 11580b7bbc7fd3ce9c32c06080639826256f0639.
