### ISSUE TITLE
Remove For All Users Check Box

### ISSUE THREAD

**Issue by stup5erman** [Teraskull/PyDebloatX#5]
**Is your feature request related to a problem? Please describe.**
No issue, just throwing ideas out.

**Describe the solution you'd like**
The Remove-AppXPackage has an -AllUsers switch that allows for the app to be removed from all user accoutns. This requires your script to be run as admin. If compiling it with pyinstaller, you can add the admin switch using --uac-admin to it.

**Describe alternatives you've considered**
It would just be nice to be able to remove the bloat from all users versus the individual user by default.

**Additional context**
subprocess.Popen(f"powershell (Get-AppxPackage -Package {self.checkbox_dict[i]} | Remove-AppxPackage -AllUsers)")

**Comment by Teraskull** [comment]
Good idea. I will think about a good implementation of this. Either the GUI will always run as admin (which is bad, if you don't have admin rights), or it will elevate the admin rights after selecting the "Remove For All Users".

**Comment by stup5erman** [comment]
You should be able to call Powershell using a runas verb from a different powershell window.

**Comment by Teraskull** [comment]
I will look into this, thanks.

**Comment by Teraskull** [comment]
@stup5erman Unfortunately, I won't add ```-AllUsers``` as it is not safe and breaks things. I tested on calculator, and now I can't reinstall it using PowerShell. 

Workaround is to install Calculator with Microsoft Store, then register the app manifest in PowerShell so that ```Get-AppxPackage``` works.

**Comment by stup5erman** [comment]
That's fine. I work for an enterprise and we remove features from all users per STIGs. I could see where regular users would want to have better options.

**Comment by Teraskull** [comment]
@stup5erman I might add it in the future, but with a warning to proceed only if you know what you are doing.
