### ISSUE TITLE
[FEATURE]  Add Support To Remove Microsoft Edge & Edge DevTools

### ISSUE THREAD

**Issue by ghost** [Teraskull/PyDebloatX#54]
Microsoft Edge & Edge DevTools is also a bloatware. Hope you will add support to remove these

**Comment by Teraskull** [comment]
I will see if it's possible to remove Edge without breaking anything in Windows. Thanks.

As I can see, in PowerShell, this command returns installed software, so should be possible.
```powershell
get-appxpackage *edge*
```

**Comment by ghost** [comment]
Welcome bro !
You can also work for insider editions too. Insider edition has so many new UWP/Metro Apps added. You can also add support for those app removal too. I suggest you to add feature removal too. And removal should be applicable for allusers not just current user. You can also add removal of `C:\Windows\SystemApps` too So it will actually delete those apps too. Or add options to delete `C:\Program Files\WindowsApps`
You can  get more lists and ideas from software like `WinReducer, NTLite, Windows 10 Sophia Scripts` (@farag2)

**Comment by Teraskull** [comment]
I don't really want to mess with `C:\Windows\SystemApps` since that would require admin rights and will break my idea of the software being safe.

**Comment by ghost** [comment]
`NSudo` can do that

**Comment by BL4CKH47H4CK3R** [comment]
`NSudo` can do that
